name: Godot CI/CD - Deploy to Github Pages

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch: # Enables manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          
          # Unzip to current directory
          unzip Godot_v4.3-stable_linux.x86_64.zip

          # Make sure it's executable (should be named Godot_v4.3-stable_linux.x86_64
          chmod +x Godot_v4.3-stable_linux.x86_64

      - name: Export Game (HTML5)
        run: |
          mkdir -p build
          ./Godot_v4.3-stable_linux.x86_64 --headless --export-release "HTML5" build/index.html

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
